import { AlertItem, AreaCompliance, Inspection, KPIData, Maintenance, Resource } from "./types/types";

export const initialKpi: KPIData = {
  inspectionCompliance: 87,
  maintenanceCompleted: 45,
  maintenanceScheduled: 52,
  pendingActions: 12,
  completedActions: 28,
  expiringResources: 8,
  totalResources: 156,
  activeAlerts: 5,
  monthlyInspections: 24,
  safetyScore: 92,
  efficiency: 94,
};

export const initialResources: Resource[] = [
  {
    id: 1,
    name: "Extintor A-101",
    group: "Extintores",
    status: "good",
    nextMaintenance: "2025-02-15",
    location: "Planta Baja",
    lastInspection: "2025-01-10",
    condition: 95,
  },
  {
    id: 2,
    name: "Botiquín B-205",
    group: "Primeros Auxilios",
    status: "warning",
    nextMaintenance: "2025-01-20",
    location: "Segundo Piso",
    lastInspection: "2025-01-08",
    condition: 72,
  },
  {
    id: 3,
    name: "Salida Emergencia C-301",
    group: "Salidas",
    status: "critical",
    nextMaintenance: "2025-01-10",
    location: "Tercer Piso",
    lastInspection: "2025-01-05",
    condition: 58,
  },
  {
    id: 4,
    name: "Detector Humo D-102",
    group: "Detectores",
    status: "good",
    nextMaintenance: "2025-03-01",
    location: "Planta Baja",
    lastInspection: "2025-01-12",
    condition: 98,
  },
  {
    id: 5,
    name: "Extintor A-102",
    group: "Extintores",
    status: "good",
    nextMaintenance: "2025-02-20",
    location: "Planta Baja",
    lastInspection: "2025-01-11",
    condition: 92,
  },
  {
    id: 6,
    name: "Botiquín B-206",
    group: "Primeros Auxilios",
    status: "good",
    nextMaintenance: "2025-02-25",
    location: "Segundo Piso",
    lastInspection: "2025-01-09",
    condition: 88,
  },
  {
    id: 7,
    name: "Salida Emergencia C-302",
    group: "Salidas",
    status: "warning",
    nextMaintenance: "2025-01-25",
    location: "Tercer Piso",
    lastInspection: "2025-01-07",
    condition: 70,
  },
  {
    id: 8,
    name: "Detector Humo D-103",
    group: "Detectores",
    status: "good",
    nextMaintenance: "2025-03-05",
    location: "Primer Piso",
    lastInspection: "2025-01-13",
    condition: 96,
  },
  {
    id: 9,
    name: "Extintor A-201",
    group: "Extintores",
    status: "warning",
    nextMaintenance: "2025-01-18",
    location: "Segundo Piso",
    lastInspection: "2025-01-06",
    condition: 68,
  },
  {
    id: 10,
    name: "Extintor A-301",
    group: "Extintores",
    status: "good",
    nextMaintenance: "2025-02-28",
    location: "Tercer Piso",
    lastInspection: "2025-01-14",
    condition: 94,
  },
  {
    id: 11,
    name: "Botiquín B-101",
    group: "Primeros Auxilios",
    status: "good",
    nextMaintenance: "2025-03-10",
    location: "Planta Baja",
    lastInspection: "2025-01-15",
    condition: 91,
  },
  {
    id: 12,
    name: "Detector Humo D-201",
    group: "Detectores",
    status: "warning",
    nextMaintenance: "2025-01-22",
    location: "Segundo Piso",
    lastInspection: "2025-01-04",
    condition: 75,
  },
];

export const initialInspections: Inspection[] = [
  {
    id: 1,
    title: "Inspección Extintores Planta 1",
    type: "Mensual",
    status: "completed",
    date: "2025-01-10",
    responsible: "Juan Pérez",
    score: 95,
    findings: 2,
  },
  {
    id: 2,
    title: "Revisión Botiquines",
    type: "Trimestral",
    status: "pending",
    date: "2025-01-15",
    responsible: "María García",
    score: null,
    findings: 0,
  },
  {
    id: 3,
    title: "Inspección Salidas Emergencia",
    type: "Mensual",
    status: "in-progress",
    date: "2025-01-12",
    responsible: "Carlos López",
    score: null,
    findings: 3,
  },
  {
    id: 4,
    title: "Revisión Detectores Humo",
    type: "Semestral",
    status: "scheduled",
    date: "2025-01-20",
    responsible: "Ana Martín",
    score: null,
    findings: 0,
  },
  {
    id: 5,
    title: "Inspección Sistema Eléctrico",
    type: "Mensual",
    status: "completed",
    date: "2025-01-08",
    responsible: "Luis Rodríguez",
    score: 88,
    findings: 4,
  },
  {
    id: 6,
    title: "Revisión Equipos Protección",
    type: "Trimestral",
    status: "pending",
    date: "2025-01-18",
    responsible: "Sofia Ramírez",
    score: null,
    findings: 0,
  },
  {
    id: 7,
    title: "Inspección Señalización",
    type: "Mensual",
    status: "completed",
    date: "2025-01-09",
    responsible: "Diego Torres",
    score: 92,
    findings: 1,
  },
  {
    id: 8,
    title: "Revisión Iluminación Emergencia",
    type: "Semestral",
    status: "in-progress",
    date: "2025-01-14",
    responsible: "Laura Díaz",
    score: null,
    findings: 2,
  },
  {
    id: 9,
    title: "Inspección Rutas Evacuación",
    type: "Mensual",
    status: "completed",
    date: "2025-01-07",
    responsible: "Pedro Sánchez",
    score: 90,
    findings: 3,
  },
  {
    id: 10,
    title: "Revisión Sistema Contra Incendios",
    type: "Trimestral",
    status: "pending",
    date: "2025-01-25",
    responsible: "Carmen Ruiz",
    score: null,
    findings: 0,
  },
];

export const initialMaintenance: Maintenance[] = [
  {
    id: 1,
    title: "Recarga Extintor A-101",
    type: "Preventivo",
    status: "completed",
    date: "2025-01-08",
    technician: "ServTec SAS",
  },
  {
    id: 2,
    title: "Cambio Batería Detector D-102",
    type: "Correctivo",
    status: "pending",
    date: "2025-01-16",
    technician: "Mantenimiento Interno",
  },
  {
    id: 3,
    title: "Revisión Sistema Alarma",
    type: "Preventivo",
    status: "in-progress",
    date: "2025-01-14",
    technician: "AlarmTech",
  },
  {
    id: 4,
    title: "Actualización Señalética",
    type: "Mejora",
    status: "scheduled",
    date: "2025-01-22",
    technician: "Señales Pro",
  },
  {
    id: 5,
    title: "Recarga Extintor A-102",
    type: "Preventivo",
    status: "completed",
    date: "2025-01-09",
    technician: "ServTec SAS",
  },
  {
    id: 6,
    title: "Reposición Botiquín B-205",
    type: "Preventivo",
    status: "pending",
    date: "2025-01-17",
    technician: "MedSupply",
  },
  {
    id: 7,
    title: "Prueba Sistema Emergencia",
    type: "Preventivo",
    status: "scheduled",
    date: "2025-01-21",
    technician: "SafetyTech",
  },
  {
    id: 8,
    title: "Reparación Salida C-301",
    type: "Correctivo",
    status: "in-progress",
    date: "2025-01-15",
    technician: "Mantenimiento Interno",
  },
  {
    id: 9,
    title: "Calibración Detectores",
    type: "Preventivo",
    status: "completed",
    date: "2025-01-06",
    technician: "TechSafety",
  },
  {
    id: 10,
    title: "Instalación Cámaras Seguridad",
    type: "Mejora",
    status: "scheduled",
    date: "2025-01-28",
    technician: "SecureTech",
  },
];

export const monthlyData = [
  {
    month: "Jul",
    inspections: 12,
    maintenance: 8,
    compliance: 85,
    incidents: 2,
  },
  {
    month: "Ago",
    inspections: 15,
    maintenance: 10,
    compliance: 88,
    incidents: 1,
  },
  {
    month: "Sep",
    inspections: 18,
    maintenance: 12,
    compliance: 92,
    incidents: 0,
  },
  {
    month: "Oct",
    inspections: 14,
    maintenance: 9,
    compliance: 89,
    incidents: 1,
  },
  {
    month: "Nov",
    inspections: 16,
    maintenance: 11,
    compliance: 91,
    incidents: 0,
  },
  {
    month: "Dic",
    inspections: 13,
    maintenance: 7,
    compliance: 87,
    incidents: 2,
  },
  {
    month: "Ene",
    inspections: 19,
    maintenance: 14,
    compliance: 93,
    incidents: 0,
  },
];

export const complianceByArea: AreaCompliance[] = [
  { area: "Planta Baja", compliance: 95, resources: 45, priority: "high" },
  { area: "Primer Piso", compliance: 88, resources: 38, priority: "medium" },
  { area: "Segundo Piso", compliance: 92, resources: 42, priority: "high" },
  { area: "Tercer Piso", compliance: 85, resources: 31, priority: "low" },
];

export const alertsData: AlertItem[] = [
  {
    id: 1,
    message: "Extintor A-101 próximo a mantenimiento",
    type: "warning",
    time: "2 horas",
  },
  {
    id: 2,
    message: "Inspección mensual pendiente",
    type: "critical",
    time: "1 día",
  },
  {
    id: 3,
    message: "Salida C-301 requiere atención inmediata",
    type: "critical",
    time: "30 min",
  },
  {
    id: 4,
    message: "Mantenimiento preventivo completado",
    type: "success",
    time: "3 horas",
  },
  {
    id: 5,
    message: "Nueva capacitación disponible",
    type: "info",
    time: "5 horas",
  },
];